
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int END_STMT = 34;
  public static final int VAL = 9;
  public static final int STRING_LITERAL = 54;
  public static final int LTE = 45;
  public static final int LBRACKET = 27;
  public static final int POT = 22;
  public static final int MULT = 39;
  public static final int CHAR = 7;
  public static final int CHAR_LITERAL = 55;
  public static final int LPAREN = 23;
  public static final int NUM_INT = 56;
  public static final int INT = 4;
  public static final int MINUS = 38;
  public static final int FOR = 14;
  public static final int WRITE = 18;
  public static final int RPAREN = 24;
  public static final int NOT = 52;
  public static final int AND = 50;
  public static final int SEMICOLON = 31;
  public static final int LT = 44;
  public static final int OR = 51;
  public static final int COMMA = 32;
  public static final int INC = 42;
  public static final int DIV = 40;
  public static final int PLUS = 37;
  public static final int ASSIGN = 33;
  public static final int MAIN = 3;
  public static final int IF = 10;
  public static final int ID = 53;
  public static final int R_ARRAY_IDX = 30;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 15;
  public static final int RBRACKET = 28;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int LBLOCK = 25;
  public static final int MOD = 21;
  public static final int NEQ = 49;
  public static final int L_ARRAY_INIT = 35;
  public static final int BREAK = 16;
  public static final int VOID = 2;
  public static final int EQ = 48;
  public static final int GTE = 47;
  public static final int RBLOCK = 26;
  public static final int COLON = 29;
  public static final int ELSE = 12;
  public static final int READ = 17;
  public static final int WHILE = 13;
  public static final int FLOAT = 5;
  public static final int INT_DIV = 41;
  public static final int R_ARRAY_INIT = 36;
  public static final int STRING = 8;
  public static final int NUM_FLOAT = 57;
  public static final int DEC = 43;
  public static final int FALSE = 20;
  public static final int GT = 46;
  public static final int ELIF = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "MAIN",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "VAL",
  "IF",
  "ELIF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "READ",
  "WRITE",
  "TRUE",
  "FALSE",
  "MOD",
  "POT",
  "LPAREN",
  "RPAREN",
  "LBLOCK",
  "RBLOCK",
  "LBRACKET",
  "RBRACKET",
  "COLON",
  "R_ARRAY_IDX",
  "SEMICOLON",
  "COMMA",
  "ASSIGN",
  "END_STMT",
  "L_ARRAY_INIT",
  "R_ARRAY_INIT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "INT_DIV",
  "INC",
  "DEC",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "EQ",
  "NEQ",
  "AND",
  "OR",
  "NOT",
  "ID",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "NUM_INT",
  "NUM_FLOAT"
  };
}

